- name: Demo on variables
  hosts: all
  vars:
     URL: sample.com
  tasks:
    - name: print URL variable
      ansible.builtin.debug:
       msg: "{{ URL }}"

# Value starts with a variable, like msg: "{{ URL }}" then quotes are needed, if it does not start with variable like msg:

