- name: Demo on variables
  hosts: localhost
  vars:
     URL: sample.com
  tasks:
    - name: print URL variable
      ansible.builtin.debug:
       msg: "{{ URL }}"

    - include: register-variable.yml

# Value starts with a variable, like msg: {{ URL }} then quotes are needed, if it does not start with variable like msg:

- name: Demo on Task variables
  hosts: localhost
  vars:
    URL: sample.com
    URL1: sample.com
    URL2: sample.com
  tasks:
    - name: print URL1 variable
      ansible.builtin.debug:
        msg: "{{ URL1 }}"
    - name: print URL2 variable
      ansible.builtin.debug:
        msg: "{{ URL2 }}"


