- name: Register Variable Example
  hosts: localhost
  tasks:
    -name: get uptime of server
    ansible.builtin.shell: uptime
    register: OUT
- name: print OUT var
  ansible.builtin.debug:
    msg: "{{ out }}"